name: Release
on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8

      - name: Build
        run: |
          TSV=$(date +%y.%m.%d).$(echo 60*$(date +%H)+$(date +%M) | bc)
          dotnet pack -c release -o nuget /p:Version=$TSV
          dotnet nuget push "nuget/*.nupkg" --skip-duplicate -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
